# Generated by Django 3.2.7 on 2023-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231010_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(0, 'added'), (1, 'check files'), (2, 'inprogress')], default=0),
        ),
    ]
