# Generated by Django 3.2.7 on 2023-10-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_domain_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1255, unique=True)),
                ('mimetype', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=20)),
                ('endtimestamp', models.CharField(max_length=20)),
                ('groupcount', models.IntegerField()),
                ('uniqcount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(3, 'Done'), (2, 'Inprogress'), (1, 'ToDo'), (0, 'Error')], default=1)),
                ('content', models.TextField(blank=True, max_length=314572800, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domain')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
    ]
