# Generated by Django 3.2.7 on 2023-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='status',
            field=models.IntegerField(choices=[(3, 'Done'), (2, 'Inprogress'), (1, 'ToDo'), (0, 'Error')], default=1),
        ),
    ]
