# Generated by Django 3.2.7 on 2023-10-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='history',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='shots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
