# Generated by Django 3.2.7 on 2023-10-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231011_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
