# Generated by Django 3.2.7 on 2023-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proxy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks4', 'SOCKS4'), ('socks5', 'SOCKS5')], default='http', max_length=10),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.IntegerField(choices=[(0, 'valid'), (1, 'error'), (2, 'stop')], default=0),
        ),
    ]
