# Generated by Django 3.2.7 on 2023-10-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231011_0758'),
        ('core', '0013_auto_20231011_0952'),
    ]

    operations = [
    ]
