# Generated by Django 3.2.7 on 2023-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_0013_auto_20231011_0758_0013_auto_20231011_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='audio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='capture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='first_captured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_captured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='snippet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='stripped_snippet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='thumb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='video',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='domain',
            name='webpage',
            field=models.IntegerField(default=0),
        ),
    ]
