# Generated by Django 3.2.7 on 2023-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20231011_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='status',
            field=models.IntegerField(choices=[(0, 'added'), (1, 'done'), (2, 'inprogress'), (3, 'error')], default=0),
        ),
    ]
