# Generated by Django 3.2.7 on 2023-10-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231017_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='user',
        ),
    ]
