# Generated by Django 3.2.7 on 2023-10-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='image_domain', verbose_name='Image')),
                ('domain_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images_domain', to='core.domain')),
            ],
            options={
                'verbose_name': 'Domain Image',
                'verbose_name_plural': 'Domain Images',
            },
        ),
    ]
