# Generated by Django 3.2.7 on 2023-10-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_domainimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(0, 'added'), (1, 'check files'), (2, 'inprogress'), (3, 'get images'), (4, 'checked'), (5, 'get files')], default=0),
        ),
    ]
