# Generated by Django 4.0 on 2023-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_domain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.IntegerField(choices=[(0, 'added'), (1, 'check files'), (2, 'inprogress'), (3, 'get images'), (4, 'checked'), (5, 'get files'), (6, 'timestamps')], default=0),
        ),
    ]
