# Generated by Django 3.2.7 on 2023-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_domain_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='status_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
