# Generated by Django 3.2.7 on 2023-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20231023_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='digest',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shot',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
