# Generated by Django 3.2.7 on 2024-01-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_proxy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='indomains',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='indomains_do',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='inlinks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='inlinks_do',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
