# Generated by Django 3.2.7 on 2024-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20240119_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ahrefs',
            field=models.BooleanField(default=False),
        ),
    ]
