# Generated by Django 3.2.7 on 2024-02-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_domain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='mimetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
